---
name: etcd-with-ssl

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: consul
  version: latest
- name: etcd
  version: latest

instance_groups:
- name: consul
  azs: [z1, z2, z3]
  instances: 3
  persistent_disk_type: 1GB
  vm_type: default
  stemcell: default
  networks: [{name: private}]
  jobs:
  - name: consul_agent
    release: consul
    provides:
      consul_common:
        as: common_link
        shared: true
      consul_server: {as: server_link}
      consul_client:
        as: client_link
        shared: true
    consumes:
      consul_common: {from: common_link}
      consul_server: {from: server_link}
      consul_client: {from: client_link}
      consul: nil
    properties:
      consul:
        agent:
          mode: server
          domain: cf.internal
        encrypt_keys:
        - "((consul_encrypt_key))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_agent.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"

- name: etcd
  azs: [z1, z2, z3]
  instances: 3
  persistent_disk_type: 1GB
  vm_type: default
  stemcell: default
  networks: [{name: private}]
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: common_link}
      consul_server: nil
      consul_client: {from: client_link}
      consul: nil
    properties:
      consul:
        agent:
          services:
            etcd: {}
  - name: etcd
    release: etcd
    consumes:
      etcd: {from: etcd_server}
    provides:
      etcd: {as: etcd_server}
    properties:
      etcd:
        peer_require_ssl: true
        require_ssl: true
        advertise_urls_dns_suffix: etcd.service.cf.internal
        heartbeat_interval_in_milliseconds: 50
        ca_cert: ((etcd_client.ca))
        client_cert: ((etcd_client.certificate))
        client_key: ((etcd_client.private_key))
        peer_ca_cert: ((etcd_peer.ca))
        peer_cert: ((etcd_peer.certificate))
        peer_key: ((etcd_peer.private_key))
        server_cert: ((etcd_server.certificate))
        server_key: ((etcd_server.private_key))

update:
  serial: true
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
- name: etcd_ca
  type: certificate
  options:
    is_ca: true
    common_name: etcdCA
- name: etcd_server
  type: certificate
  options:
    ca: etcd_ca
    common_name: etcd.service.cf.internal
    alternative_names:
    - "*.etcd.service.cf.internal"
    - etcd.service.cf.internal
    - "*.cf-etcd.service.cf.internal"
    - cf-etcd.service.cf.internal
    extended_key_usage:
    - server_auth
- name: etcd_client
  type: certificate
  options:
    ca: etcd_ca
    common_name: clientName
    extended_key_usage:
    - client_auth
- name: etcd_peer_ca
  type: certificate
  options:
    is_ca: true
    common_name: peerCA
- name: etcd_peer
  type: certificate
  options:
    ca: etcd_peer_ca
    common_name: etcd.service.cf.internal
    alternative_names:
    - "*.etcd.service.cf.internal"
    - etcd.service.cf.internal
    - "*.cf-etcd.service.cf.internal"
    - cf-etcd.service.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
- name: consul_agent_ca
  type: certificate
  options:
    is_ca: true
    common_name: consulCA
- name: consul_agent
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: consul_agent
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
- name: consul_server
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: server.dc1.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
- name: consul_encrypt_key
  type: password
