name: etcd

instance_groups:
- name: consul
  azs:
  - z1
  instances: 1
  persistent_disk_type: 1GB
  vm_type: default
  stemcell: default
  update:
    max_in_flight: 1
    serial: true
  networks:
  - name: private
    static_ips: &consul_ips
    - 10.0.31.190
  jobs:
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: server
          domain: cf.internal
          servers: &consul_machines
            lan: *consul_ips
        encrypt_keys:
        - "((consul_encrypt_key))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_agent.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"
- name: etcd
  azs:
  - z1
  - z2
  - z3
  instances: 3
  persistent_disk_type: 5GB
  vm_type: m3.medium
  vm_extensions:
  - 5GB_ephemeral_disk
  stemcell: default
  update:
    serial: true
    max_in_flight: 1
  networks:
  - name: private
  jobs:
  - name: consul_agent
    release: consul
    properties:
      consul:
        agent:
          mode: client
          domain: cf.internal
          servers: *consul_machines
          services:
            etcd: {}
        encrypt_keys:
        - "((consul_encrypt_key))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_agent.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"
  - name: etcd
    release: etcd
    properties:
      etcd:
        advertise_urls_dns_suffix: etcd.service.cf.internal
        cluster:
        - instances: 3
          name: etcd
        peer_require_ssl: true
        require_ssl: true
        ca_cert: "((etcd_client.ca))"
        client_cert: "((etcd_client.certificate))"
        client_key: "((etcd_client.private_key))"
        server_cert: "((etcd_server.certificate))"
        server_key: "((etcd_server.private_key))"
        peer_ca_cert: "((etcd_peer.ca))"
        peer_cert: "((etcd_peer.certificate))"
        peer_key: "((etcd_peer.private_key))"

update:
  canary_watch_time: 1000-180000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-180000
  canaries: 1

releases:
- name: etcd
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release
  version: latest
- name: consul
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

variables:
- name: etcd_ca
  type: certificate
  options:
    common_name: etcdCA
- name: etcd_server
  type: certificate
  options:
    ca: etcd_ca
    common_name: etcd.service.cf.internal
    alternative_names:
    - "*.etcd.service.cf.internal"
    - etcd.service.cf.internal
    ext_key_usage:
    - server_auth
- name: etcd_client
  type: certificate
  options:
    ca: etcd_ca
    common_name: clientName
    ext_key_usage:
    - client_auth
- name: etcd_peer_ca
  type: certificate
  options:
    common_name: peerCA
- name: etcd_peer
  type: certificate
  options:
    ca: etcd_peer_ca
    common_name: etcd.service.cf.internal
    alternative_names:
    - "*.etcd.service.cf.internal"
    - etcd.service.cf.internal
    ext_key_usage:
    - client_auth
    - server_auth
- name: consul_encrypt_key
  type: password
- name: consul_agent_ca
  type: certificate
  options:
    common_name: consulCA
- name: consul_agent
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: consul_agent
    ext_key_usage:
    - client_auth
    - server_auth
- name: consul_server
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: server.dc1.cf.internal
    ext_key_usage:
    - client_auth
    - server_auth
